# This file was generated by GoReleaser. DO NOT EDIT.
cask "devdash" do
  name "devdash"
  desc "Dev process dashboard TUI — launch, monitor, and manage local dev services"
  homepage "https://github.com/kimaguri/simplx-toolkit"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devdash"

  on_macos do
    on_intel do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/devdash_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "2c996e9a4ee55dd8c7f00f678aa28fa6b289353b99fbcfde6bf0da5a94112175"
    end
    on_arm do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/devdash_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "344fc10afa7ab66b29633942211f7926be8b247f953afd0ae1feb4c52b0f6127"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/devdash_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "00419eccf3b97afca2ee69933ffc40e5b129314c505c68c366bf5adfb65b701e"
    end
    on_arm do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/devdash_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "0f2ab5a6bb177af052f95c4f19238dc4a1e3986c89426726a2cce915e6126fc7"
    end
  end

  # No zap stanza required
end
