# This file was generated by GoReleaser. DO NOT EDIT.
cask "local" do
  name "local"
  desc "Dev process dashboard TUI — launch, monitor, and manage local dev services"
  homepage "https://github.com/kimaguri/simplx-toolkit"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local"

  on_macos do
    on_intel do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/local_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "b60b6b61df2a0dcdd411a6a3188be2e249d405a32c57c420cdd9eec195f52a4a"
    end
    on_arm do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/local_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "f01434639548c97df21cbdbaf52a6f8e8b793523c49c603bccdcb8555d1ad8d6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/local_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "9fe3e7f775dd681eb14f3f6a1dc7c916f993686d9e53feb3154dd52ab7ad97e1"
    end
    on_arm do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/local_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "3fafa59333a8e2e19dd91382865f13e6338717cc87cc837258e06b2329711a74"
    end
  end

  # No zap stanza required
end
