# This file was generated by GoReleaser. DO NOT EDIT.
cask "local" do
  name "local"
  desc "Dev process dashboard TUI — launch, monitor, and manage local dev services"
  homepage "https://github.com/kimaguri/simplx-toolkit"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "local"

  on_macos do
    on_intel do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/local_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "256d96b6f86e792e08403a677d21a59dc5c41ac15f6ec300bfbf14c85ab040aa"
    end
    on_arm do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/local_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "d99a9711be286fe915331536f1bbefaa1f13a99f0c123dfacc8fcd2b4fa218b6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/local_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "7a51bc3c4d69ec4d81fae85866dddbfd068185cd1534b92e88e2ad1543b86ce0"
    end
    on_arm do
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v#{version}/local_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kimaguri/simplx-toolkit"
      sha256 "5b8c59627178a179a65ff71379c7f07c0fd0e27a48bf5b9f0aebe9c7730652ed"
    end
  end

  # No zap stanza required
end
