# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devdash < Formula
  desc "Dev process dashboard TUI — launch, monitor, and manage local dev services"
  homepage "https://github.com/kimaguri/simplx-toolkit"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.5.0/devdash_0.5.0_darwin_amd64.tar.gz"
      sha256 "e2757fb8336780bcc2b2ab46c69ddd0d1d00a39a8a56710d33d1cbea82b5f221"

      define_method(:install) do
        bin.install "devdash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.5.0/devdash_0.5.0_darwin_arm64.tar.gz"
      sha256 "f1f492309e18fedf552b86273d164c90501dc971f014af08c2eed205589b0325"

      define_method(:install) do
        bin.install "devdash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.5.0/devdash_0.5.0_linux_amd64.tar.gz"
      sha256 "e58a0420a6630013e8a729f97256ac0e08be1d6656facbce9770cefb6c7e2410"
      define_method(:install) do
        bin.install "devdash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.5.0/devdash_0.5.0_linux_arm64.tar.gz"
      sha256 "e3c4739e2e84f077ec6ba99114b77b90d0f55d8a25bd613de6158f5fd05b079a"
      define_method(:install) do
        bin.install "devdash"
      end
    end
  end
end
