# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devdash < Formula
  desc "Dev process dashboard TUI — launch, monitor, and manage local dev services"
  homepage "https://github.com/kimaguri/simplx-toolkit"
  version "0.10.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.10.0/devdash_0.10.0_darwin_amd64.tar.gz"
      sha256 "9c7bc61bf2998eb657cbfcb4d3fa8f5e5f8e5ddda5352578253186f5f46e7ef9"

      define_method(:install) do
        bin.install "devdash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.10.0/devdash_0.10.0_darwin_arm64.tar.gz"
      sha256 "7b9630218bc1fe1c364d5f4bb160cdddc50c97e0ca094266fd217506c13d143a"

      define_method(:install) do
        bin.install "devdash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.10.0/devdash_0.10.0_linux_amd64.tar.gz"
      sha256 "80e156b040718b2e72761964a4d491614acc57cbcf39c04597d28b5f816e7ea2"
      define_method(:install) do
        bin.install "devdash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.10.0/devdash_0.10.0_linux_arm64.tar.gz"
      sha256 "89d006f1981ceb38d792658c17c9a8d74cdc97e6efa8b5f1b7ceac0ef0215be9"
      define_method(:install) do
        bin.install "devdash"
      end
    end
  end
end
