# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devdash < Formula
  desc "Dev process dashboard TUI — launch, monitor, and manage local dev services"
  homepage "https://github.com/kimaguri/simplx-toolkit"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.3.2/devdash_0.3.2_darwin_amd64.tar.gz"
      sha256 "d130b608be64bdbd8dc85c87a472f23b51e4c8cb23a758940d4aee9febf825c4"

      def install
        bin.install "devdash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.3.2/devdash_0.3.2_darwin_arm64.tar.gz"
      sha256 "6069629d769dc2553db396c5ea59bc52ac876779b2f1e142d157dd13beebc609"

      def install
        bin.install "devdash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.3.2/devdash_0.3.2_linux_amd64.tar.gz"
      sha256 "c6adc4e6f0cd8a83dca5cd6d8a93045c9058dd424659e9bcf3fd8cd48d9bb149"
      def install
        bin.install "devdash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.3.2/devdash_0.3.2_linux_arm64.tar.gz"
      sha256 "98f95775680d1ca77427023ea4799416edf5dfd67b3ef6af155e667293cddfb6"
      def install
        bin.install "devdash"
      end
    end
  end
end
