# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maomao < Formula
  desc "Multi-repo agent orchestrator — manage AI agents across git repositories"
  homepage "https://github.com/kimaguri/simplx-toolkit"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.4.0/maomao_0.4.0_darwin_amd64.tar.gz"
      sha256 "1c49def688c1cc8088797f01e9638e04b7dcd002e6766adfd2ad49ed8c71db18"

      define_method(:install) do
        bin.install "maomao"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.4.0/maomao_0.4.0_darwin_arm64.tar.gz"
      sha256 "4be20b819909f990e9a67e1ee7a69cac7c772661134f735ef6e8ea58ee48e1bb"

      define_method(:install) do
        bin.install "maomao"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.4.0/maomao_0.4.0_linux_amd64.tar.gz"
      sha256 "107a4401caf5ff9d5c524e37d0d6fedbb07c448fafdfea12957c577a59588939"
      define_method(:install) do
        bin.install "maomao"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.4.0/maomao_0.4.0_linux_arm64.tar.gz"
      sha256 "416462d575720d692e92b2569e642ef87d15c1a78db5d5178b80ed6df0bd4663"
      define_method(:install) do
        bin.install "maomao"
      end
    end
  end
end
