# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maomao < Formula
  desc "Multi-repo agent orchestrator — manage AI agents across git repositories"
  homepage "https://github.com/kimaguri/simplx-toolkit"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.6.0/maomao_0.6.0_darwin_amd64.tar.gz"
      sha256 "2b538ba2ee269ddf0b37d8c2a601de25cee7e31405b12e35a0ca7339f486434a"

      define_method(:install) do
        bin.install "maomao"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.6.0/maomao_0.6.0_darwin_arm64.tar.gz"
      sha256 "e622bec40b838a00373a70fcdacecea51d66988cfeec39345d1f37f2a06d0c83"

      define_method(:install) do
        bin.install "maomao"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.6.0/maomao_0.6.0_linux_amd64.tar.gz"
      sha256 "384bd18287ab2486065c350c42e6bbb8933a0cb5c1fe4c436f5811f50fc38acd"
      define_method(:install) do
        bin.install "maomao"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kimaguri/simplx-toolkit/releases/download/v0.6.0/maomao_0.6.0_linux_arm64.tar.gz"
      sha256 "b9fe9d05271b123efe8a11ce3f887e52379cb01e8d09c5fa67ea7e4aaac475f5"
      define_method(:install) do
        bin.install "maomao"
      end
    end
  end
end
